### ISSUE TITLE
Why is the README on Github not the same as the README on NPM?

### ISSUE THREAD

**Issue by joshuapinter** [AndersDJohnson/use-yarn#13]
### Github
![image](https://user-images.githubusercontent.com/180819/90203163-36f74480-dd9d-11ea-9f00-029c1917b895.png)

### NPM
![image](https://user-images.githubusercontent.com/180819/90203178-44143380-dd9d-11ea-91a9-e76a7319cc3f.png)

The one on NPM has all the installation and usage information that one would want. I'm genuinely curious why this is the case but also I think the README on Github should be the same to include the install and usage instructions.

Thanks!

**Comment by AndersDJohnson** [comment]
@joshuapinter Thanks for your interest in this little utility! I was actually in progress transitioning the docs to a website (https://andersdjohnson.com/code/use-yarn), but I guess I haven't yet published that to change `npm`. Anyway, either docs location is still accurate and valid, no worries!

**Comment by joshuapinter** [comment]
Oh, I see. Sounds good and thanks.
