### ISSUE TITLE
Feat: environment variable override

### ISSUE THREAD

**Issue by jimthedev** [AndersDJohnson/use-yarn#4]
Is it possible to offer an environment variable to override this check? For example I want end-users to use yarn but now.sh installs using both. It isn't a problem but being able to have the check for people who are cloning but to override in specific scenarios would be handy.

**Comment by AndersDJohnson** [comment]
@jimthedev Good idea. Yes, we can easily support that. Something like `NO_USE_YARN=true`, or what would you prefer?

**Comment by jimthedev** [comment]
DISABLE_USE_YARN=true?

**Comment by AndersDJohnson** [comment]
@jimthedev Sure. I may have time to implement this tonight. Or a PR is welcome of course.
