### ISSUE TITLE
Feature request: print the correct yarn command in error message

### ISSUE THREAD

**Issue by muescha** [AndersDJohnson/use-yarn#8]
it should print the correct yarn command in error message.

for example when i copy paste from some documentation or tutorials:

```
npm install mypackage --save-dev
```

it should print out:

```
you can use yarn with this command:

yarn add mypackage --dev
```

**Comment by AndersDJohnson** [comment]
@muescha That is a cool idea. Would you be interested in opening a pull request?

**Comment by AndersDJohnson** [comment]
I believe `preinstall` hook we wire up `use-yarn` with may only run for `npm install` alone and not on `npm install [pkg]` for specific packages. So I'm not sure this is feasible at this time. 😢
