### ISSUE TITLE
Add a big warning on project description about limitations when installing specific packages

### ISSUE THREAD

**Issue by aalexgabi** [AndersDJohnson/use-yarn#9]
use-yarn does not work in all cases. For example when installing a specific package: `npm install lodash`. I think this should be clearly stated on the project landing page as it's one of the main ways to get yarn.lock out of sync with the node_modules folder.

Related report: https://npm.community/t/preinstall-npm-hook-doesnt-execute-when-installing-a-specific-package/2505

**Comment by aalexgabi** [comment]
> If run from npm instead of yarn, the process will exit with error code 1 and print an error message.

Currently this is stated in the description. It would be more accurate to specifically mention `npm install` (without a package name)

**Comment by AndersDJohnson** [comment]
@aalexgabi Good call! Completed in #14. May not publish the docs site immediately.
